language: go
go:
  - 1.15.x

sudo: required
services:
  - docker

env:
  - CODECOV_TOKEN=d13aebe2-7368-47e7-9280-d0664086386f

script:
  - go mod download
  - go test $(go list ./... | grep -v /testfiles/) -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
