apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: corpus-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corpus
  serviceName: corpus-svc-headless
  template:
    metadata:
      labels:
        app: corpus
    spec:
      containers:
      - image: google.com/corpus:v2.0.0
        imagePullPolicy: Always
        name: corpus
        ports:
        - containerPort: 6060
          name: http-port
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: corpus-svc-headless
spec:
  selector:
    app: corpus
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
  clusterIP: None